{% set name = "json_stream" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/json-stream-{{ version }}.tar.gz
  sha256: 5c36fb544be702c71a6b081364fb5b1a3128d63541223c3e864f50be6e4eecea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.5,<4.0
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.5,<4.0
    - json-stream-rs-tokenizer >=0.4.16

test:
  imports:
    - json_stream
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Streaming JSON encoder and decoder
  home: https://github.com/daggaz/json-stream
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
